name: Tests
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag stellar_occultations .
    - name: Corre pruebas y evalúa la cobertura
      run: docker run stellar_occultations make coverage
    - name: Evalua resistencia a mutaciones
      run: docker run stellar_occultations make mutants